# Generated by Django 2.2 on 2019-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wild', '0002_auto_20190407_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tours',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
